### ISSUE TITLE
Implement API Key Management Routes

### ISSUE THREAD

**Issue by ivanLOliveira** [diconium/ethereal-pulse#23]
## Description
We need to create a set of API endpoints to manage API keys. These endpoints should allow users with a valid API key to:
1. Create new API keys.
2. List all API keys associated with their user account.
3. Delete an API key.

### 1. Create API Key

- **Route**: `POST /api/keys`
- **Description**: Allows a user to create a new API key by providing their user ID and a valid API key.
- **Request Body**:
  ```json
  {
    "userId": "string",
    "currentApiKey": "string"
  }
  ```
- **Response**:
  ```json
  {
    "apiKey": "string",
    "message": "API key created successfully"
  }
  ```
- **Errors**:
    - 401 Unauthorized: Invalid API key.
    - 400 Bad Request: Missing or invalid userId.

### 2. List API Keys

- **Route**: `GET /api/keysv`
- **Description**:  Allows a user to create a new API key by providing their user ID and a valid API key.
- **Headers**:
  ```json
  {
  "Authorization": "Bearer <currentApiKey>"
  }
  ```
- **Response**:
  ```json
  {
    "apiKeys": [
      {
        "id": "string",
        "apiKey": "string",
        "createdAt": "string"
      }
    ]
  }
  ```
- **Errors**:
    - 401 Unauthorized: Invalid API key.
### 3. Delete API Keys

- **Route**: `DELETE /api/keys`
- **Description**:  Deletes a API key.
- **Resquest Body**:
  ```json
  {
    "apiKey": "string"
  }
  ```
- **Response**:
  ```json
  {
    "message": "API key deleted successfully"
  }
  ```
- **Errors**:
    - 401 Unauthorized: Invalid API key.
    - 400 Bad Request: Missing or invalid `apiKey`.
## Tasks

1. Implement the **Create API Key** route.
2. Implement the **List API Keys** route.
3. Implement the **Delete API Key** route.
4. Add validation for API keys.
5. Add error handling for each endpoint.
6. Write tests for each endpoint to ensure they work as expected.

## Additional Context

- Ensure the API key operations are secure and follow best practices for authentication and authorization.
- Store the API keys securely in the database, ensuring they are hashed or encrypted.
- This task is part of Phase 2 of our development roadmap.

## Labels

`backend`, `api`, `enhancement`

## Acceptance Criteria

- [ ] A user can create a new API key by providing their user ID and a valid API key.
- [ ] A user can list all API keys associated with their account using a valid API key.
- [ ] A user can delete an API key by providing the API key to be deleted.
- [ ] Proper validation is in place for API keys.
- [ ] Error handling is implemented for each endpoint.
- [ ] Tests are written and passing for all endpoints.
