### ISSUE TITLE
Define API specifications

### ISSUE THREAD

**Issue by almeiphi** [diconium/ethereal-pulse#6]
#### Description
We need to define the API specification for our project, which will serve as a blueprint for the backend development. The specification should cover all the endpoints, request/response formats, authentication mechanisms, and error handling.

#### Tasks
1. **Research and Choose Tools**
   - Determine the tools and frameworks for defining the API spec (e.g., Swagger, OpenAPI).
   
2. **Outline API Endpoints**
   - List all the necessary API endpoints for user authentication, email management, and integration services.
   - Define the HTTP methods for each endpoint (GET, POST, PUT, DELETE).
   
3. **Define Request/Response Formats**
   - Specify the request parameters and body for each endpoint.
   - Define the response formats, including status codes and data structures.
   
4. **Authentication Mechanism**
   - Define the API key authentication mechanism.
   - Outline how API keys will be validated and managed.
   
5. **Error Handling**
   - Establish a standard format for error responses.
   - Define common error codes and their meanings.
   
6. **Document the API Spec**
   - Use Swagger or OpenAPI to create the API documentation.
   - Ensure the documentation is comprehensive and clear.
   
7. **Review and Feedback**
   - Share the API specification with the team for review.
   - Incorporate feedback and make necessary adjustments.

#### Acceptance Criteria
- [ ] A complete list of API endpoints with defined HTTP methods.
- [ ] Detailed request and response formats for each endpoint.
- [ ] Clear description of the API key authentication mechanism.
- [ ] Standardized error handling format.
- [ ] Comprehensive API documentation created using Swagger or OpenAPI.
- [ ] Reviewed and approved by the team.

#### Additional Notes
- Refer to existing API documentation best practices for guidance.
- Ensure the API spec is scalable and can accommodate future integrations.

---

**Labels**: `API`, `Documentation`, `Backend`
**Assignees**: `@almeiphi`

---

### Reference Links
- [Swagger Documentation](https://swagger.io/docs/)
- [OpenAPI Specification](https://swagger.io/specification/)

**Comment by almeiphi** [comment]
The initial Swagger API documentation for our microservices has been included in the related [discussion thread](https://github.com/diconium/ethereal-pulse/discussions/12).

**Comment by almeiphi** [comment]
Updating the proposal yaml by adding the 'from:string' and 'cloudProviderCredentials' properties and unifying the `/send` endpoint

```yaml
swagger: '2.0'
info:
  description: >-
    This is the Swagger API documentation for the Ethereal Pulse Microservice API. It allows authenticated users to send emails using Azure Communication Services or AWS Simple Email Service.
  version: "1.0.0"
  title: Ethereal Pulse Microservice API
host: api.yourdomain.com
basePath: /v1
schemes:
  - https
paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticates user and returns a JWT token
      tags:
        - Authentication
      parameters:
        - in: body
          name: body
          description: User credentials
          required: true
          schema:
            $ref: '#/definitions/LoginUser'
      responses:
        200:
          description: JWT token
          schema:
            $ref: '#/definitions/TokenResponse'
        401:
          description: Unauthorized

  /email/send:
    post:
      summary: Send email
      description: Sends an email to specified recipients using the selected provider with customer credentials
      tags:
        - Email
      security:
        - ApiKeyAuth: []
        - Bearer: []
      parameters:
        - in: body
          name: body
          description: Email details
          required: true
          schema:
            $ref: '#/definitions/SendEmailRequest'
      responses:
        200:
          description: Email sent successfully
        400:
          description: Bad Request
        401:
          description: Unauthorized

  /templates:
    get:
      summary: Get user templates
      description: Retrieves all email templates for authenticated user
      tags:
        - Template
      security:
        - Bearer: []
      responses:
        200:
          description: List of email templates
          schema:
            type: array
            items:
              $ref: '#/definitions/Template'
        401:
          description: Unauthorized

    post:
      summary: Create new template
      description: Creates a new email template for authenticated user
      tags:
        - Template
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          description: Template details
          required: true
          schema:
            $ref: '#/definitions/Template'
      responses:
        201:
          description: Template created successfully
        400:
          description: Bad Request
        401:
          description: Unauthorized

    put:
      summary: Update template
      description: Updates an existing email template for authenticated user
      tags:
        - Template
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          description: Template details
          required: true
          schema:
            $ref: '#/definitions/Template'
      responses:
        200:
          description: Template updated successfully
        400:
          description: Bad Request
        401:
          description: Unauthorized

  /groups:
    get:
      summary: Get user groups
      description: Retrieves all recipient groups for authenticated user
      tags:
        - Group
      security:
        - Bearer: []
      responses:
        200:
          description: List of recipient groups
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
        401:
          description: Unauthorized

    post:
      summary: Create new group
      description: Creates a new recipient group for authenticated user
      tags:
        - Group
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          description: Group details
          required: true
          schema:
            $ref: '#/definitions/Group'
      responses:
        201:
          description: Group created successfully
        400:
          description: Bad Request
        401:
          description: Unauthorized

    put:
      summary: Update group
      description: Updates an existing recipient group for authenticated user
      tags:
        - Group
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          description: Group details
          required: true
          schema:
            $ref: '#/definitions/Group'
      responses:
        200:
          description: Group updated successfully
        400:
          description: Bad Request
        401:
          description: Unauthorized

  /groups/{groupId}:
    delete:
      summary: Delete group
      description: Deletes a recipient group
      tags:
        - Group
      security:
        - Bearer: []
      parameters:
        - in: path
          name: groupId
          required: true
          type: string
      responses:
        200:
          description: Group deleted successfully
        401:
          description: Unauthorized

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: JWT token for webapp authentication

  ApiKeyAuth:
    type: apiKey
    name: x-api-key
    in: header
    description: Multi-tenant API keys for SDK authentication

definitions:
  LoginUser:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password

  TokenResponse:
    type: object
    properties:
      token:
        type: string

  SendEmailRequest:
    type: object
    properties:
      provider:
        type: string
        enum:
          - azure
          - aws
      cloudProviderCredentials:
        type: object
        properties:
          accountId:
            type: string
          accountKey:
            type: string
      from:
        type: string
      recipients:
        type: array
        items:
          type: string
      subject:
        type: string
      htmlContent:
        type: string
    required:
      - provider
      - cloudProviderCredentials
      - from
      - recipients
      - subject
      - htmlContent

  Template:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      subject:
        type: string
      htmlContent:
        type: string
    required:
      - name
      - subject
      - htmlContent

  Group:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      recipients:
        type: array
        items:
          type: string
    required:
      - name
      - recipients
  ```
