### ISSUE TITLE
Implementation of templates resource in the SDK

### ISSUE THREAD

**Issue by danielfernandes2022** [diconium/ethereal-pulse#92]
## Description

We need to implement the templates resource in the SDK.

## Pre-Condition

1. **Templates endpoint is already implemented in the API**.

## Tasks

1. **Implement Get templates**:

2. **Implement Post templates**:

3. **Implement Put templates**:
   
4. **Implement Delete templates**:
   
## Labels

`SDK`, `Templates`

## Acceptance Criteria

- [ ] Should be able to fetch the templates using SDK
- [ ] Should be able to add templates using SDK
- [ ] Should be able to update templates using SDK
- [ ] Should be able to remove templates using SDK
